### ISSUE TITLE
gulp won't compile

### ISSUE THREAD

**Issue by JKonTiki** [cferdinandi/gulp-boilerplate#57]
all i've done is clone this repository, run npm install, and tried to compile with gulp. not working, here's what i'm getting:

/Users/jeremy/Desktop/_code/gulp-boilerplate/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/jeremy/Desktop/_code/gulp-boilerplate/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeremy/Desktop/_code/gulp-boilerplate/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)

**Comment by cferdinandi** [comment]
I actually just ran into this this morning as well. Candidly, I haven't updated this in some time and the build dependencies are likely quite out of date. 

I'll get around to updating them eventually, but can't commit to anything.

**Comment by JKonTiki** [comment]
no problem - thanks for the speedy response!

**Comment by cferdinandi** [comment]
This should be fixed with https://github.com/cferdinandi/gulp-boilerplate/pull/58, but please not this is a breaking update as I've removed unit testing with Jasmine and Karma.
