### ISSUE TITLE
Down on JS-file edit

### ISSUE THREAD

**Issue by BulatSa** [cferdinandi/gulp-boilerplate#98]
Hello, when i'm editing js file gulp down with error. Have to restart every time. 
But on editing HTML and SCSS files all normal.

`Starting 'copyFiles'...
(node:15192) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token: punc (})
    at js_error (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:538:11)
    at croak (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:1251:9)
    at token_error (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:1259:9)
    at unexpected (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:1265:9)
    at as_name (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:3024:33)
    at subscripts (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:3099:30)
    at expr_atom (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:2486:20)
    at maybe_unary (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:3234:19)
    at expr_ops (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:3285:24)
    at maybe_conditional (D:\Projects\avgvst\node_modules\terser\dist\bundle.min.js:3290:20)
(node:15192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by cferdinandi** [comment]
Hi all, I'm not longer maintaining this project, and recommend you instead use my [Build Tool Boilerplate](https://github.com/cferdinandi/build-tool-boilerplate).
